// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package vinyl

type User struct {
	UserID      int64  `db:"user_id"`
	UserName    string `db:"user_name"`
	DateCreated string `db:"date_created"`
}

type UserVinylPlay struct {
	UserID      int64   `db:"user_id"`
	VinylID     int64   `db:"vinyl_id"`
	Plays       int64   `db:"plays"`
	FirstPlayed *string `db:"first_played"`
	LastPlayed  *string `db:"last_played"`
}

type VinylUnique struct {
	VinylID           int64   `db:"vinyl_id"`
	VinylTitle        string  `db:"vinyl_title"`
	VinylArtist       string  `db:"vinyl_artist"`
	VinylPressingYear int64   `db:"vinyl_pressing_year"`
	FirstPressing     int64   `db:"first_pressing"`
	DiscogsMasterID   *int64  `db:"discogs_master_id"`
	Styles            *string `db:"styles"`
	Genres            *string `db:"genres"`
	ImageExtension    string  `db:"image_extension"`
	CoverRawBlob      []byte  `db:"cover_raw_blob"`
	CoverEmbedding    []byte  `db:"cover_embedding"`
}
