// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package vinyl

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(
    user_name, date_created
) VALUES (?, ?)
RETURNING user_id, user_name, date_created
`

type CreateUserParams struct {
	UserName    string `db:"user_name"`
	DateCreated string `db:"date_created"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.UserName, arg.DateCreated)
	var i User
	err := row.Scan(&i.UserID, &i.UserName, &i.DateCreated)
	return i, err
}

const getAllVinyls = `-- name: GetAllVinyls :many
SELECT vinyl_id, vinyl_title, vinyl_artist, vinyl_pressing_year, first_pressing, image_extension, cover_raw_blob, cover_embedding FROM vinyl_unique
`

func (q *Queries) GetAllVinyls(ctx context.Context) ([]VinylUnique, error) {
	rows, err := q.query(ctx, q.getAllVinylsStmt, getAllVinyls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VinylUnique{}
	for rows.Next() {
		var i VinylUnique
		if err := rows.Scan(
			&i.VinylID,
			&i.VinylTitle,
			&i.VinylArtist,
			&i.VinylPressingYear,
			&i.FirstPressing,
			&i.ImageExtension,
			&i.CoverRawBlob,
			&i.CoverEmbedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerVinyl = `-- name: RegisterVinyl :one
INSERT INTO vinyl_unique(
    vinyl_title, vinyl_artist, vinyl_pressing_year,
    first_pressing, image_extension,
    cover_raw_blob, cover_embedding
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING vinyl_id, vinyl_title, vinyl_artist, vinyl_pressing_year, first_pressing, image_extension, cover_raw_blob, cover_embedding
`

type RegisterVinylParams struct {
	VinylTitle        string `db:"vinyl_title"`
	VinylArtist       string `db:"vinyl_artist"`
	VinylPressingYear int64  `db:"vinyl_pressing_year"`
	FirstPressing     int64  `db:"first_pressing"`
	ImageExtension    string `db:"image_extension"`
	CoverRawBlob      []byte `db:"cover_raw_blob"`
	CoverEmbedding    []byte `db:"cover_embedding"`
}

func (q *Queries) RegisterVinyl(ctx context.Context, arg RegisterVinylParams) (VinylUnique, error) {
	row := q.queryRow(ctx, q.registerVinylStmt, registerVinyl,
		arg.VinylTitle,
		arg.VinylArtist,
		arg.VinylPressingYear,
		arg.FirstPressing,
		arg.ImageExtension,
		arg.CoverRawBlob,
		arg.CoverEmbedding,
	)
	var i VinylUnique
	err := row.Scan(
		&i.VinylID,
		&i.VinylTitle,
		&i.VinylArtist,
		&i.VinylPressingYear,
		&i.FirstPressing,
		&i.ImageExtension,
		&i.CoverRawBlob,
		&i.CoverEmbedding,
	)
	return i, err
}
