// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package vinyl

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(user_name) VALUES (?)
RETURNING user_id, user_name, date_created
`

func (q *Queries) CreateUser(ctx context.Context, userName string) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, userName)
	var i User
	err := row.Scan(&i.UserID, &i.UserName, &i.DateCreated)
	return i, err
}

const deleteVinyl = `-- name: DeleteVinyl :exec
DELETE FROM vinyl_unique WHERE vinyl_id = ?
`

func (q *Queries) DeleteVinyl(ctx context.Context, vinylID int64) error {
	_, err := q.exec(ctx, q.deleteVinylStmt, deleteVinyl, vinylID)
	return err
}

const getAllVinyls = `-- name: GetAllVinyls :many
SELECT vinyl_id, vinyl_title, vinyl_artist, vinyl_pressing_year, first_pressing, discogs_master_id, styles, genres, image_extension, cover_raw_blob, cover_embedding FROM vinyl_unique
`

func (q *Queries) GetAllVinyls(ctx context.Context) ([]VinylUnique, error) {
	rows, err := q.query(ctx, q.getAllVinylsStmt, getAllVinyls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VinylUnique{}
	for rows.Next() {
		var i VinylUnique
		if err := rows.Scan(
			&i.VinylID,
			&i.VinylTitle,
			&i.VinylArtist,
			&i.VinylPressingYear,
			&i.FirstPressing,
			&i.DiscogsMasterID,
			&i.Styles,
			&i.Genres,
			&i.ImageExtension,
			&i.CoverRawBlob,
			&i.CoverEmbedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVinylPlays = `-- name: GetUserVinylPlays :many
SELECT user_id, vinyl_id, plays, first_played, last_played FROM user_vinyl_plays WHERE user_id = ?
`

func (q *Queries) GetUserVinylPlays(ctx context.Context, userID int64) ([]UserVinylPlay, error) {
	rows, err := q.query(ctx, q.getUserVinylPlaysStmt, getUserVinylPlays, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserVinylPlay{}
	for rows.Next() {
		var i UserVinylPlay
		if err := rows.Scan(
			&i.UserID,
			&i.VinylID,
			&i.Plays,
			&i.FirstPlayed,
			&i.LastPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playVinylCollection = `-- name: PlayVinylCollection :one
UPDATE user_vinyl_plays
SET 
    plays = plays + 1,
    last_played = date('now')
WHERE
    user_id = ? AND vinyl_id = ?
RETURNING user_id, vinyl_id, plays, first_played, last_played
`

type PlayVinylCollectionParams struct {
	UserID  int64 `db:"user_id"`
	VinylID int64 `db:"vinyl_id"`
}

func (q *Queries) PlayVinylCollection(ctx context.Context, arg PlayVinylCollectionParams) (UserVinylPlay, error) {
	row := q.queryRow(ctx, q.playVinylCollectionStmt, playVinylCollection, arg.UserID, arg.VinylID)
	var i UserVinylPlay
	err := row.Scan(
		&i.UserID,
		&i.VinylID,
		&i.Plays,
		&i.FirstPlayed,
		&i.LastPlayed,
	)
	return i, err
}

const recordVinylCollection = `-- name: RecordVinylCollection :one
INSERT INTO user_vinyl_plays (user_id, vinyl_id, plays)
VALUES (?, ?, 0)
ON CONFLICT(user_id, vinyl_id)
DO UPDATE SET 
    plays = plays + 1,
    first_played = COALESCE(first_played, date('now')),
    last_played = date('now')
RETURNING user_id, vinyl_id, plays, first_played, last_played
`

type RecordVinylCollectionParams struct {
	UserID  int64 `db:"user_id"`
	VinylID int64 `db:"vinyl_id"`
}

func (q *Queries) RecordVinylCollection(ctx context.Context, arg RecordVinylCollectionParams) (UserVinylPlay, error) {
	row := q.queryRow(ctx, q.recordVinylCollectionStmt, recordVinylCollection, arg.UserID, arg.VinylID)
	var i UserVinylPlay
	err := row.Scan(
		&i.UserID,
		&i.VinylID,
		&i.Plays,
		&i.FirstPlayed,
		&i.LastPlayed,
	)
	return i, err
}

const registerVinyl = `-- name: RegisterVinyl :one
INSERT INTO vinyl_unique(
    vinyl_title, vinyl_artist, vinyl_pressing_year,
    first_pressing, discogs_master_id, styles, genres,
    image_extension, cover_raw_blob, cover_embedding
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(vinyl_title, vinyl_artist, vinyl_pressing_year)
DO UPDATE SET vinyl_title = vinyl_title
RETURNING vinyl_id, vinyl_title, vinyl_artist, vinyl_pressing_year, first_pressing, discogs_master_id, styles, genres, image_extension, cover_raw_blob, cover_embedding
`

type RegisterVinylParams struct {
	VinylTitle        string  `db:"vinyl_title"`
	VinylArtist       string  `db:"vinyl_artist"`
	VinylPressingYear int64   `db:"vinyl_pressing_year"`
	FirstPressing     int64   `db:"first_pressing"`
	DiscogsMasterID   *int64  `db:"discogs_master_id"`
	Styles            *string `db:"styles"`
	Genres            *string `db:"genres"`
	ImageExtension    string  `db:"image_extension"`
	CoverRawBlob      []byte  `db:"cover_raw_blob"`
	CoverEmbedding    []byte  `db:"cover_embedding"`
}

// RETURNING only fires on rows that are written. DO NOTHING suppresses the
// write, so RETURNING returns nothing. The no-op SET forces a write, giving
// RETURNING the row to return. https://sqlite.org/forum/forumpost/6c153c0a6e224091
func (q *Queries) RegisterVinyl(ctx context.Context, arg RegisterVinylParams) (VinylUnique, error) {
	row := q.queryRow(ctx, q.registerVinylStmt, registerVinyl,
		arg.VinylTitle,
		arg.VinylArtist,
		arg.VinylPressingYear,
		arg.FirstPressing,
		arg.DiscogsMasterID,
		arg.Styles,
		arg.Genres,
		arg.ImageExtension,
		arg.CoverRawBlob,
		arg.CoverEmbedding,
	)
	var i VinylUnique
	err := row.Scan(
		&i.VinylID,
		&i.VinylTitle,
		&i.VinylArtist,
		&i.VinylPressingYear,
		&i.FirstPressing,
		&i.DiscogsMasterID,
		&i.Styles,
		&i.Genres,
		&i.ImageExtension,
		&i.CoverRawBlob,
		&i.CoverEmbedding,
	)
	return i, err
}
