// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package vinyl

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.deleteUserVinylPlaysStmt, err = db.PrepareContext(ctx, deleteUserVinylPlays); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserVinylPlays: %w", err)
	}
	if q.deleteVinylStmt, err = db.PrepareContext(ctx, deleteVinyl); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteVinyl: %w", err)
	}
	if q.ensureOwnershipPlayStmt, err = db.PrepareContext(ctx, ensureOwnershipPlay); err != nil {
		return nil, fmt.Errorf("error preparing query EnsureOwnershipPlay: %w", err)
	}
	if q.findExistingVinylIDByMasterIDStmt, err = db.PrepareContext(ctx, findExistingVinylIDByMasterID); err != nil {
		return nil, fmt.Errorf("error preparing query FindExistingVinylIDByMasterID: %w", err)
	}
	if q.getAllUserVinylPlaysStmt, err = db.PrepareContext(ctx, getAllUserVinylPlays); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUserVinylPlays: %w", err)
	}
	if q.getAllVinylRecordsStmt, err = db.PrepareContext(ctx, getAllVinylRecords); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllVinylRecords: %w", err)
	}
	if q.getCurrentReleaseIDStmt, err = db.PrepareContext(ctx, getCurrentReleaseID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCurrentReleaseID: %w", err)
	}
	if q.getMyVinylStmt, err = db.PrepareContext(ctx, getMyVinyl); err != nil {
		return nil, fmt.Errorf("error preparing query GetMyVinyl: %w", err)
	}
	if q.getPrimaryReleaseIDStmt, err = db.PrepareContext(ctx, getPrimaryReleaseID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPrimaryReleaseID: %w", err)
	}
	if q.getReleaseBlobLengthsStmt, err = db.PrepareContext(ctx, getReleaseBlobLengths); err != nil {
		return nil, fmt.Errorf("error preparing query GetReleaseBlobLengths: %w", err)
	}
	if q.getReleaseCandidateRowStmt, err = db.PrepareContext(ctx, getReleaseCandidateRow); err != nil {
		return nil, fmt.Errorf("error preparing query GetReleaseCandidateRow: %w", err)
	}
	if q.getReleaseCoverStmt, err = db.PrepareContext(ctx, getReleaseCover); err != nil {
		return nil, fmt.Errorf("error preparing query GetReleaseCover: %w", err)
	}
	if q.getReleaseMasterFlagStmt, err = db.PrepareContext(ctx, getReleaseMasterFlag); err != nil {
		return nil, fmt.Errorf("error preparing query GetReleaseMasterFlag: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserVinylPlaysStmt, err = db.PrepareContext(ctx, getUserVinylPlays); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserVinylPlays: %w", err)
	}
	if q.getVinylRecordByIDStmt, err = db.PrepareContext(ctx, getVinylRecordByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetVinylRecordByID: %w", err)
	}
	if q.insertVinylPlayStmt, err = db.PrepareContext(ctx, insertVinylPlay); err != nil {
		return nil, fmt.Errorf("error preparing query InsertVinylPlay: %w", err)
	}
	if q.listOwnedPressingsStmt, err = db.PrepareContext(ctx, listOwnedPressings); err != nil {
		return nil, fmt.Errorf("error preparing query ListOwnedPressings: %w", err)
	}
	if q.listPressingOptionRowsStmt, err = db.PrepareContext(ctx, listPressingOptionRows); err != nil {
		return nil, fmt.Errorf("error preparing query ListPressingOptionRows: %w", err)
	}
	if q.listReleaseScanRowsStmt, err = db.PrepareContext(ctx, listReleaseScanRows); err != nil {
		return nil, fmt.Errorf("error preparing query ListReleaseScanRows: %w", err)
	}
	if q.listUserScanRowsStmt, err = db.PrepareContext(ctx, listUserScanRows); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserScanRows: %w", err)
	}
	if q.listUserVinylPlayDatesStmt, err = db.PrepareContext(ctx, listUserVinylPlayDates); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserVinylPlayDates: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.nextPlayNumberStmt, err = db.PrepareContext(ctx, nextPlayNumber); err != nil {
		return nil, fmt.Errorf("error preparing query NextPlayNumber: %w", err)
	}
	if q.registerVinylUniqueStmt, err = db.PrepareContext(ctx, registerVinylUnique); err != nil {
		return nil, fmt.Errorf("error preparing query RegisterVinylUnique: %w", err)
	}
	if q.upsertVinylReleaseStmt, err = db.PrepareContext(ctx, upsertVinylRelease); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertVinylRelease: %w", err)
	}
	if q.upsertVinylReleaseCheckStmt, err = db.PrepareContext(ctx, upsertVinylReleaseCheck); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertVinylReleaseCheck: %w", err)
	}
	if q.userOwnsMasterStmt, err = db.PrepareContext(ctx, userOwnsMaster); err != nil {
		return nil, fmt.Errorf("error preparing query UserOwnsMaster: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.deleteUserVinylPlaysStmt != nil {
		if cerr := q.deleteUserVinylPlaysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserVinylPlaysStmt: %w", cerr)
		}
	}
	if q.deleteVinylStmt != nil {
		if cerr := q.deleteVinylStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteVinylStmt: %w", cerr)
		}
	}
	if q.ensureOwnershipPlayStmt != nil {
		if cerr := q.ensureOwnershipPlayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing ensureOwnershipPlayStmt: %w", cerr)
		}
	}
	if q.findExistingVinylIDByMasterIDStmt != nil {
		if cerr := q.findExistingVinylIDByMasterIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findExistingVinylIDByMasterIDStmt: %w", cerr)
		}
	}
	if q.getAllUserVinylPlaysStmt != nil {
		if cerr := q.getAllUserVinylPlaysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUserVinylPlaysStmt: %w", cerr)
		}
	}
	if q.getAllVinylRecordsStmt != nil {
		if cerr := q.getAllVinylRecordsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllVinylRecordsStmt: %w", cerr)
		}
	}
	if q.getCurrentReleaseIDStmt != nil {
		if cerr := q.getCurrentReleaseIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCurrentReleaseIDStmt: %w", cerr)
		}
	}
	if q.getMyVinylStmt != nil {
		if cerr := q.getMyVinylStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMyVinylStmt: %w", cerr)
		}
	}
	if q.getPrimaryReleaseIDStmt != nil {
		if cerr := q.getPrimaryReleaseIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPrimaryReleaseIDStmt: %w", cerr)
		}
	}
	if q.getReleaseBlobLengthsStmt != nil {
		if cerr := q.getReleaseBlobLengthsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReleaseBlobLengthsStmt: %w", cerr)
		}
	}
	if q.getReleaseCandidateRowStmt != nil {
		if cerr := q.getReleaseCandidateRowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReleaseCandidateRowStmt: %w", cerr)
		}
	}
	if q.getReleaseCoverStmt != nil {
		if cerr := q.getReleaseCoverStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReleaseCoverStmt: %w", cerr)
		}
	}
	if q.getReleaseMasterFlagStmt != nil {
		if cerr := q.getReleaseMasterFlagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReleaseMasterFlagStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserVinylPlaysStmt != nil {
		if cerr := q.getUserVinylPlaysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserVinylPlaysStmt: %w", cerr)
		}
	}
	if q.getVinylRecordByIDStmt != nil {
		if cerr := q.getVinylRecordByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVinylRecordByIDStmt: %w", cerr)
		}
	}
	if q.insertVinylPlayStmt != nil {
		if cerr := q.insertVinylPlayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertVinylPlayStmt: %w", cerr)
		}
	}
	if q.listOwnedPressingsStmt != nil {
		if cerr := q.listOwnedPressingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOwnedPressingsStmt: %w", cerr)
		}
	}
	if q.listPressingOptionRowsStmt != nil {
		if cerr := q.listPressingOptionRowsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPressingOptionRowsStmt: %w", cerr)
		}
	}
	if q.listReleaseScanRowsStmt != nil {
		if cerr := q.listReleaseScanRowsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listReleaseScanRowsStmt: %w", cerr)
		}
	}
	if q.listUserScanRowsStmt != nil {
		if cerr := q.listUserScanRowsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserScanRowsStmt: %w", cerr)
		}
	}
	if q.listUserVinylPlayDatesStmt != nil {
		if cerr := q.listUserVinylPlayDatesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserVinylPlayDatesStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.nextPlayNumberStmt != nil {
		if cerr := q.nextPlayNumberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing nextPlayNumberStmt: %w", cerr)
		}
	}
	if q.registerVinylUniqueStmt != nil {
		if cerr := q.registerVinylUniqueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing registerVinylUniqueStmt: %w", cerr)
		}
	}
	if q.upsertVinylReleaseStmt != nil {
		if cerr := q.upsertVinylReleaseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertVinylReleaseStmt: %w", cerr)
		}
	}
	if q.upsertVinylReleaseCheckStmt != nil {
		if cerr := q.upsertVinylReleaseCheckStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertVinylReleaseCheckStmt: %w", cerr)
		}
	}
	if q.userOwnsMasterStmt != nil {
		if cerr := q.userOwnsMasterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userOwnsMasterStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                DBTX
	tx                                *sql.Tx
	createUserStmt                    *sql.Stmt
	deleteUserStmt                    *sql.Stmt
	deleteUserVinylPlaysStmt          *sql.Stmt
	deleteVinylStmt                   *sql.Stmt
	ensureOwnershipPlayStmt           *sql.Stmt
	findExistingVinylIDByMasterIDStmt *sql.Stmt
	getAllUserVinylPlaysStmt          *sql.Stmt
	getAllVinylRecordsStmt            *sql.Stmt
	getCurrentReleaseIDStmt           *sql.Stmt
	getMyVinylStmt                    *sql.Stmt
	getPrimaryReleaseIDStmt           *sql.Stmt
	getReleaseBlobLengthsStmt         *sql.Stmt
	getReleaseCandidateRowStmt        *sql.Stmt
	getReleaseCoverStmt               *sql.Stmt
	getReleaseMasterFlagStmt          *sql.Stmt
	getUserByIDStmt                   *sql.Stmt
	getUserVinylPlaysStmt             *sql.Stmt
	getVinylRecordByIDStmt            *sql.Stmt
	insertVinylPlayStmt               *sql.Stmt
	listOwnedPressingsStmt            *sql.Stmt
	listPressingOptionRowsStmt        *sql.Stmt
	listReleaseScanRowsStmt           *sql.Stmt
	listUserScanRowsStmt              *sql.Stmt
	listUserVinylPlayDatesStmt        *sql.Stmt
	listUsersStmt                     *sql.Stmt
	nextPlayNumberStmt                *sql.Stmt
	registerVinylUniqueStmt           *sql.Stmt
	upsertVinylReleaseStmt            *sql.Stmt
	upsertVinylReleaseCheckStmt       *sql.Stmt
	userOwnsMasterStmt                *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                tx,
		tx:                                tx,
		createUserStmt:                    q.createUserStmt,
		deleteUserStmt:                    q.deleteUserStmt,
		deleteUserVinylPlaysStmt:          q.deleteUserVinylPlaysStmt,
		deleteVinylStmt:                   q.deleteVinylStmt,
		ensureOwnershipPlayStmt:           q.ensureOwnershipPlayStmt,
		findExistingVinylIDByMasterIDStmt: q.findExistingVinylIDByMasterIDStmt,
		getAllUserVinylPlaysStmt:          q.getAllUserVinylPlaysStmt,
		getAllVinylRecordsStmt:            q.getAllVinylRecordsStmt,
		getCurrentReleaseIDStmt:           q.getCurrentReleaseIDStmt,
		getMyVinylStmt:                    q.getMyVinylStmt,
		getPrimaryReleaseIDStmt:           q.getPrimaryReleaseIDStmt,
		getReleaseBlobLengthsStmt:         q.getReleaseBlobLengthsStmt,
		getReleaseCandidateRowStmt:        q.getReleaseCandidateRowStmt,
		getReleaseCoverStmt:               q.getReleaseCoverStmt,
		getReleaseMasterFlagStmt:          q.getReleaseMasterFlagStmt,
		getUserByIDStmt:                   q.getUserByIDStmt,
		getUserVinylPlaysStmt:             q.getUserVinylPlaysStmt,
		getVinylRecordByIDStmt:            q.getVinylRecordByIDStmt,
		insertVinylPlayStmt:               q.insertVinylPlayStmt,
		listOwnedPressingsStmt:            q.listOwnedPressingsStmt,
		listPressingOptionRowsStmt:        q.listPressingOptionRowsStmt,
		listReleaseScanRowsStmt:           q.listReleaseScanRowsStmt,
		listUserScanRowsStmt:              q.listUserScanRowsStmt,
		listUserVinylPlayDatesStmt:        q.listUserVinylPlayDatesStmt,
		listUsersStmt:                     q.listUsersStmt,
		nextPlayNumberStmt:                q.nextPlayNumberStmt,
		registerVinylUniqueStmt:           q.registerVinylUniqueStmt,
		upsertVinylReleaseStmt:            q.upsertVinylReleaseStmt,
		upsertVinylReleaseCheckStmt:       q.upsertVinylReleaseCheckStmt,
		userOwnsMasterStmt:                q.userOwnsMasterStmt,
	}
}
