// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package vinyl

type User struct {
	UserID      int64  `db:"user_id"`
	UserName    string `db:"user_name"`
	DateCreated string `db:"date_created"`
}

type VinylPlay struct {
	UserID     int64  `db:"user_id"`
	VinylID    int64  `db:"vinyl_id"`
	ReleaseID  int64  `db:"release_id"`
	Play       int64  `db:"play"`
	PlayedDate string `db:"played_date"`
}

type VinylRelease struct {
	VinylID          int64    `db:"vinyl_id"`
	ReleaseID        int64    `db:"release_id"`
	LowestPrice      *float64 `db:"lowest_price"`
	PriceLastUpdated *string  `db:"price_last_updated"`
	Country          *string  `db:"country"`
	Notes            *string  `db:"notes"`
	Released         string   `db:"released"`
	MasterRelease    int64    `db:"master_release"`
	ResourceUri      string   `db:"resource_uri"`
	ImageExtension   string   `db:"image_extension"`
	CoverRawBlob     []byte   `db:"cover_raw_blob"`
	CoverEmbedding   []byte   `db:"cover_embedding"`
}

type VinylReleasesCheck struct {
	VinylID       int64  `db:"vinyl_id"`
	ReleaseID     int64  `db:"release_id"`
	Label         string `db:"label"`
	Country       string `db:"country"`
	ReleaseFormat string `db:"release_format"`
	ReleasedYear  int64  `db:"released_year"`
	CoverUri      string `db:"cover_uri"`
}

type VinylUnique struct {
	VinylID     int64   `db:"vinyl_id"`
	VinylTitle  string  `db:"vinyl_title"`
	VinylArtist string  `db:"vinyl_artist"`
	MasterID    *int64  `db:"master_id"`
	MasterYear  *int64  `db:"master_year"`
	Styles      *string `db:"styles"`
	Genres      *string `db:"genres"`
}
